run6x24:
	@$(TARGET) \
		-l 6144 \
		-r 1536 \
		-b 4613 \
		-d0  \
		-i50 \
		-a625 \
		-C 24 \
		-V 6 \
		-G 256 \
		-x$(CUR_DIR)/matrix/f.csv \
		-c$(CUR_DIR)/matrix/CNsCon257_6x24.csv \
		-v$(CUR_DIR)/matrix/VNsCon257_6x24.csv \
		-s 2.5 \
		-S 0.2 \
		-E 3.5 \
		$(outfile)
