runm6x8:
	@$(TARGET) \
		-l 2048 \
		-r 1536 \
		-b 514 \
		-d0  \
		-i50 \
		-a$(attenu) \
		-C 8 \
		-V 6 \
		-G 256 \
		-x$(CUR_DIR)/matrix/f.csv \
		-c$(CUR_DIR)/matrix/CNsConMasking257_6x8.csv \
		-v$(CUR_DIR)/matrix/VNsConMasking257_6x8.csv \
		-s 2.5 \
		-S 0.2 \
		-E 3.5 \
		$(outfile)
